// <auto-generated />
using System;
using MangaApi.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MangaApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240109145831_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MangaApi.Domain.Models.Mangas.CollectionPage", b =>
                {
                    b.Property<string>("CollectionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MangaId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CollectionId");

                    b.ToTable("CollectionPages");
                });

            modelBuilder.Entity("MangaApi.Domain.Models.Mangas.Mangas", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CollectionPageCollectionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Popularity")
                        .HasColumnType("int");

                    b.Property<string>("TagsModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Translation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CollectionPageCollectionId");

                    b.HasIndex("TagsModelId")
                        .IsUnique();

                    b.ToTable("Mangas");
                });

            modelBuilder.Entity("MangaApi.Domain.Models.Mangas.PageModel", b =>
                {
                    b.Property<int?>("PageNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("PageNumber"));

                    b.Property<string>("CollectionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MangaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PageNumber");

                    b.ToTable("PageModels");
                });

            modelBuilder.Entity("MangaApi.Domain.Models.Tags.TagsModel", b =>
                {
                    b.Property<string>("TagsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MangaId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagsId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("MangaApi.Domain.Models.Mangas.Mangas", b =>
                {
                    b.HasOne("MangaApi.Domain.Models.Mangas.CollectionPage", "CollectionPage")
                        .WithMany()
                        .HasForeignKey("CollectionPageCollectionId");

                    b.HasOne("MangaApi.Domain.Models.Tags.TagsModel", "TagsModel")
                        .WithOne("Manga")
                        .HasForeignKey("MangaApi.Domain.Models.Mangas.Mangas", "TagsModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollectionPage");

                    b.Navigation("TagsModel");
                });

            modelBuilder.Entity("MangaApi.Domain.Models.Tags.TagsModel", b =>
                {
                    b.OwnsOne("System.Collections.Generic.Dictionary<string, bool>", "Tags", b1 =>
                        {
                            b1.Property<string>("TagsModelTagsId")
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("TagsModelTagsId");

                            b1.ToTable("Tags");

                            b1.WithOwner()
                                .HasForeignKey("TagsModelTagsId");
                        });

                    b.Navigation("Tags")
                        .IsRequired();
                });

            modelBuilder.Entity("MangaApi.Domain.Models.Tags.TagsModel", b =>
                {
                    b.Navigation("Manga")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
